// Problem Statement: We are given a rod of size 'N'. It can be cut into pieces. Each length of a piece has a particular price given by the price array. Our task is to find the maximum revenue that can be generated by selling the pieces of the rod.

// Problem Link: https://www.codingninjas.com/studio/problems/rod-cutting-problem_800284?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf

#include <iostream>
#include <vector>
#include <algorithm>
using namespace std;

int helper(vector<int>& price, int ind, int n, vector<vector<int>>& dp) {
    if (ind == 0) {
        return n * price[0];
    }
    if (dp[ind][n] != -1) return dp[ind][n];
    
    int notTake = helper(price, ind - 1, n, dp);
    int take = -1e9;
    int rodLength = ind + 1;
    if (rodLength <= n) {
        take = price[ind] + helper(price, ind, n - rodLength, dp);
    }
    return dp[ind][n] = max(take, notTake);
}

int cutRod(vector<int>& price, int n) {
    vector<vector<int>> dp(n, vector<int>(n + 1, -1));
    return helper(price, n - 1, n, dp);
}
