# Problem Statement: We are given a rod of size 'N'. It can be cut into pieces. Each length of a piece has a particular price given by the price array. Our task is to find the maximum revenue that can be generated by selling the pieces of the rod.

# Problem Link: https://www.codingninjas.com/studio/problems/rod-cutting-problem_800284?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf

def helper(price, ind, n, dp):
    if ind == 0:
        return n * price[0]
    
    if dp[ind][n] != -1:
        return dp[ind][n]
        
    not_take = helper(price, ind - 1, n, dp)
    take = -float('inf')
    rod_length = ind + 1
    if rod_length <= n:
        take = price[ind] + helper(price, ind, n - rod_length, dp)
        
    dp[ind][n] = max(take, not_take)
    return dp[ind][n]

def cut_rod(price, n):
    dp = [[-1] * (n + 1) for _ in range(n)]
    return helper(price, n - 1, n, dp)
